name: Build Go Binaries

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:

jobs:
  build:
    name: Build cross-platform Go program
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          PLATFORMS=(darwin/amd64 darwin/arm64 freebsd/386 freebsd/amd64 freebsd/arm freebsd/arm64 linux/386 linux/amd64 linux/arm linux/arm64)
          mkdir -p build
          EXT=""
          for p in "${PLATFORMS[@]}"; do
            export GOOS=$(echo $p | cut -d "/" -f 1)
            export GOARCH=$(echo $p | cut -d "/" -f 2)
            if [ "${GOOS}" = "windows" ]; then EXT=".exe"; fi
            go build -o build/ssh-prompter-${GOOS}-${GOARCH}${EXT}
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-prompter-${{ matrix.os }}-${{ matrix.arch }}
          path: build/ssh-prompter-${{ matrix.os }}-${{ matrix.arch }}*
