name: Build Go Binaries

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir -p build
          EXT=""
          if [ "${GOOS}" = "windows" ]; then EXT=".exe"; fi
          go build -o build/ssh-selector-${GOOS}-${GOARCH}${EXT}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-selector-${{ matrix.os }}-${{ matrix.arch }}
          path: build/ssh-selector-${{ matrix.os }}-${{ matrix.arch }}*
